---
kind: pipeline
name: build
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  pull: if-not-exists
  environment:
    IMAGE_NAME: quay.io/ukhomeofficedigital/dind-awscli
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done; if [ ! docker stats --no-stream ]; then exit 1; fi
  - docker build -t $${IMAGE_NAME}:$${DRONE_COMMIT_SHA} . --no-cache

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

trigger:
  event:
  - pull_request
  - push

---
kind: pipeline
name: publish
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: push_latest
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dind-awscli
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
  environment:
    DOCKER_PASSWORD:
      from_secret: ukhomeofficedigital+dind_awscli
    DOCKER_USERNAME: docker_password
  when:
    branch:
    - master
    event:
    - push

- name: push_tag
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dind-awscli
    tags:
      - ${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: ukhomeofficedigital+dind_awscli
    DOCKER_USERNAME: docker_password
  when:
    event:
    - tag

trigger:
  branch:
  - master
  event:
  - tag
  - push
